---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: /:year ## disables post output
timezone: null
lsi: false
markdown: kramdown
highlighter: rouge


### content configuration ###
title: LadCo Wealth
keywords: mutual fund mf equity derivatives trading wealth management 
description:
source_link:
favicon:
touch_icon:
google_analytics_key: UA-55876898-1


### template colors, used site-wide via css ###
colors:
  black:     '#111111'
  white:     '#f8f8f8'
  blue:      '#49a7e9'
  green:     '#9bcf2f'
  purple:    '#c869bf'
  orange:    '#fab125'
  turquoise: '#0fbfcf'
  greenigh:	'#63BD2F'
kramdown:
  auto_ids: false
